# Generated by Django 2.0.2 on 2018-04-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(verbose_name='created time')),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(verbose_name='created time')),
                ('description', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=2000)),
                ('react_angry', models.IntegerField()),
                ('react_haha', models.IntegerField()),
                ('react_like', models.IntegerField()),
                ('react_love', models.IntegerField()),
                ('react_sad', models.IntegerField()),
                ('react_wow', models.IntegerField()),
                ('scrape_time', models.DateTimeField(verbose_name='scrape time')),
                ('shares', models.IntegerField()),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recsys.Page')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recsys.Page'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recsys.Post'),
        ),
    ]
