# Generated by Django 2.0.2 on 2018-04-13 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0002_auto_20180413_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recsys.Page'),
        ),
    ]
