# Generated by Django 2.0.2 on 2018-04-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0004_auto_20180413_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='page_id',
            new_name='from_id',
        ),
    ]
