# Generated by Django 2.0.2 on 2018-04-08 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(verbose_name='created time')),
                ('description', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=1000)),
                ('react_angry', models.IntegerField()),
                ('react_haha', models.IntegerField()),
                ('react_like', models.IntegerField()),
                ('react_love', models.IntegerField()),
                ('react_sad', models.IntegerField()),
                ('react_wow', models.IntegerField()),
                ('scrape_time', models.DateTimeField(verbose_name='scrape time')),
                ('shares', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reviews.Page')),
            ],
        ),
    ]
